In [2]:
import pandas as pd
df = pd.read_csv("kpi_temporada.csv")
print(len(df), 'partidos hasta ahora')

1329 partidos hasta ahora

In [3]:
df.head(1)

,gameId,total,maximo,minimo,margen,prorrogas,fecha,partido,estrella_gs,mvp,nota_igualdad,nota_ritmo,nota_ot,nota_estrella,KPI
0,22500001,249,125,124,1,2,2025-10-21,OKC vs HOU,33.1,Alperen Sengun,0.95,0.816667,1.0,0.603333,84.9

# ¿Cuál fue el partido mas divertido de la temporada?

In [6]:
TOP10= df.sort_values(
    by=['KPI'],
    ascending= False
).head(10)
TOP10

,gameId,total,maximo,minimo,margen,prorrogas,fecha,partido,estrella_gs,mvp,nota_igualdad,nota_ritmo,nota_ot,nota_estrella,KPI
448,22500013,280,142,138,4,1,2025-12-25,DEN vs MIN,59.8,Nikola Jokić,0.80,1.000000,0.7,1.000000,85.0
0,22500001,249,125,124,1,2,2025-10-21,OKC vs HOU,33.1,Alperen Sengun,0.95,0.816667,1.0,0.603333,84.9
14,22500005,276,141,135,6,2,2025-10-23,IND vs OKC,43.1,Shai Gilgeous-Alexander,0.70,1.000000,1.0,0.936667,84.6
1167,22501130,270,136,134,2,1,2026-04-04,DEN vs SAS,39.3,Nikola Jokić,0.90,1.000000,0.7,0.810000,83.8
198,22500240,297,150,147,3,2,2025-11-16,UTA vs CHI,34.6,Lauri Markkanen,0.85,1.000000,1.0,0.653333,82.8
50,22500120,272,138,134,4,1,2025-10-27,UTA vs PHX,40.7,Lauri Markkanen,0.80,1.000000,0.7,0.856667,80.7
184,22500046,260,133,127,6,2,2025-11-14,DAL vs LAC,38.8,James Harden,0.70,1.000000,1.0,0.793333,80.3
148,22500199,272,137,135,2,1,2025-11-10,DET vs WAS,35.4,Cade Cunningham,0.90,1.000000,0.7,0.680000,79.9
15,22500006,268,137,131,6,1,2025-10-23,GSW vs DEN,44.2,Aaron Gordon,0.70,1.000000,0.7,0.973333,79.7
551,22500525,254,129,125,4,1,2026-01-07,OKC vs UTA,39.9,Shai Gilgeous-Alexander,0.80,0.900000,0.7,0.830000,79.4

In [5]:
mejor = TOP10.iloc[0]
print(
    f'El partido más interesante fue {mejor["partido"]} ({mejor["fecha"]}), con {mejor["mvp"]} de estrella y un KPI de {mejor["KPI"]}.'
)

El partido más interesante fue DEN vs MIN (2025-12-25), con Nikola Jokić de estrella y un KPI de 85.0.

# ¿Qué equipo fue el más divertido de ver?

In [12]:
df["equipos"] = df["partido"].str.split(" vs ")

In [18]:
# separamos en dos con el explode

df_equipos = df.explode('equipos')

In [19]:
len(df_equipos)

2658

In [22]:
# Sacamos ahora la media por equipo
kpi_por_equipos = df_equipos.groupby( by= 'equipos', as_index=False)['KPI'].mean()

kpi_por_equipos.sort_values(by='KPI', ascending= False)

   equipos        KPI
36     WLD  46.250000
8      DEN  43.296591
34     VIN  38.300000
7      DAL  37.796341
15     MEL  37.150000
11     HOU  36.784091
23     ORL  36.078022
20     NOP  35.621951
5      CHI  35.129268
10     GSW  35.121429
6      CLE  35.114000
33     UTA  35.082927
28     SAS  34.853774
9      DET  34.795833
24     PHI  34.670213
19     MIN  34.627660
14     LAL  34.410870
13     LAC  34.344578
27     SAC  34.339024
26     POR  34.255682
31     TMC  33.800000
25     PHX  33.422727
12     IND  33.374390
16     MEM  33.250000
17     MIA  32.897590
21     NYK  32.283333
0      ATL  32.246591
18     MIL  31.815854
22     OKC  31.627835
1      AUS  31.500000
3      BOS  31.269663
32     TOR  30.839326
29     STP  30.833333
4      CHA  30.169048
35     WAS  29.115854
2      BKN  27.324390
30     STR  27.000000

In [24]:
# Pillo lo de all star asi que filtramos
# 1. Contar cuántos partidos jugó cada equipo
conteo = df_equipos["equipos"].value_counts()

# 2. Quedarnos con los equipos "reales" (los que jugaron más de 50 partidos)
equipos_reales = conteo[conteo > 50].index

# 3. Filtrar df_equipos para dejar solo esos equipos
df_reales = df_equipos[df_equipos["equipos"].isin(equipos_reales)]

# 4. Media de KPI por equipo, ordenada, con índice limpio
kpi_por_equipo = (
    df_reales.groupby("equipos")["KPI"].mean()
    .sort_values(ascending=False)
    .reset_index()
)
kpi_por_equipo.index = kpi_por_equipo.index + 1   # ranking desde 1

print(kpi_por_equipo)

   equipos        KPI
1      DEN  43.296591
2      DAL  37.796341
3      HOU  36.784091
4      ORL  36.078022
5      NOP  35.621951
6      CHI  35.129268
7      GSW  35.121429
8      CLE  35.114000
9      UTA  35.082927
10     SAS  34.853774
11     DET  34.795833
12     PHI  34.670213
13     MIN  34.627660
14     LAL  34.410870
15     LAC  34.344578
16     SAC  34.339024
17     POR  34.255682
18     PHX  33.422727
19     IND  33.374390
20     MEM  33.250000
21     MIA  32.897590
22     NYK  32.283333
23     ATL  32.246591
24     MIL  31.815854
25     OKC  31.627835
26     BOS  31.269663
27     TOR  30.839326
28     CHA  30.169048
29     WAS  29.115854
30     BKN  27.324390